# Generated by Django 4.1 on 2022-08-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('website', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('qual', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('freelance', models.BooleanField(default=False)),
                ('img', models.ImageField(default='media/default.jpg', upload_to='media/')),
            ],
        ),
    ]
